config/routes.rb
Rails.application.routes.draw do
  resources :courses
  root 'pages#home'
  get 'pages/about'
  get 'pages/contact'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/course.rb
class Course < ApplicationRecord
	validates :name, presence: true, length: { minimum: 5, maximum: 50 }
	validates :code, presence: true, length: { minimum: 3, maximum: 10 }
	validates :description, presence: true, length: { minimum: 10, maximum: 500 }
	validates :start_date, presence: true
	validates :end_date, presence: true
	
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  before_action :set_course, only: [:show, :edit, :update, :destroy]

  # GET /courses
  # GET /courses.json
  def index
    @courses = Course.all
  end

  # GET /courses/1
  # GET /courses/1.json
  def show
  end

  # GET /courses/new
  def new
    @course = Course.new
  end

  # GET /courses/1/edit
  def edit
  end

  # POST /courses
  # POST /courses.json
  def create
    @course = Course.new(course_params)

    respond_to do |format|
      if @course.save
        format.html { redirect_to @course, notice: 'Course was successfully created.' }
        format.json { render :show, status: :created, location: @course }
      else
        format.html { render :new }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /courses/1
  # PATCH/PUT /courses/1.json
  def update
    respond_to do |format|
      if @course.update(course_params)
        format.html { redirect_to @course, notice: 'Course was successfully updated.' }
        format.json { render :show, status: :ok, location: @course }
      else
        format.html { render :edit }
        format.json { render json: @course.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /courses/1
  # DELETE /courses/1.json
  def destroy
    @course.destroy
    respond_to do |format|
      format.html { redirect_to courses_url, notice: 'Course was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_course
      @course = Course.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def course_params
      params.require(:course).permit(:code, :name, :description, :start_date, :end_date)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def about
  end

  def contact
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/courses/_form.html.erb
<%= form_with(model: course, local: true) do |form| %>
  <% if course.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(course.errors.count, "error") %> prohibited this course from being saved:</h2>

      <ul>
        <% course.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="row">
    <div class="input-field col s3">
      <%= form.text_field :code, class: "validate", id: "code" %>
      <label class="active" for="code">Course Code</label>
    </div>
    <div class="input-field col s9">
      <%= form.text_field :name, class: "validate", id: "name" %>
      <label class="active" for="name">Course Name</label>
    </div>
  </div>

  <div class="row">
    <div class="col s12">
      <div class="row">
        <div class="input-field col s12">
          <%= form.text_area :description, id: "description", class: "materialize-textarea" %>
          <label for="description">Description</label>
        </div>
      </div>
    </div>
  </div>
  
  <div class="row">
    <div class="input-field col s3">
      <%= form.text_field :start_date, class: "datepicker", id: "sdate" %>
      <label class="active" for="sdate">Start Date</label>
    </div>
    <div class="input-field col s3">
      <%= form.text_field :end_date, class: "datepicker", id: "edate" %>
      <label class="active" for="edate">End Date</label>
    </div>
  </div>

  <div class="actions center-align ">
    <%= button_tag(:class => "waves-effect waves-light btn submit") do %>
      <i class="material-icons left">cloud</i> Submit
    <% end %>
    <%= link_to courses_path, class: "waves-effect waves-light orange darken-1 btn btn-secondary submit" do %>
      <i class="material-icons left">close</i> Cancel
    <% end %>
  </div>
<% end %>

app/views/courses/edit.html.erb
<h1>Editing Course</h1>

<%= render 'form', course: @course %>

<%= link_to 'Show', @course %> |
<%= link_to 'Back', courses_path %>

app/views/courses/index.html.erb
<p id="notice"><%= notice %></p>

<h2 class="center-align header">Courses</h2>

<div class="row">
  <div class="col s12">
    <% @courses.each do |course| %>
      <div class="col s12 m6">
        <div class="card blue-grey darken-1">
          <div class="card-content white-text">
            <span class="card-title">
              <%= course.code %>: <%= course.name %>
            </span>
            <p><%= truncate(course.description, :length => 100 ) %></p>
            <span class="dateinfo">Start Date: <%= course.start_date.to_date.to_formatted_s(:long) %></span><br>
            
          </div>
          <div class="card-action">
            <a href="#">Enroll</a>
            <%= link_to 'Info', course %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>


<br>

<%= link_to 'New Course', new_course_path %>

app/views/courses/new.html.erb
<h2 class="center-align header">New Course</h2>

<%= render 'form', course: @course %>

app/views/courses/show.html.erb
<p id="notice"><%= notice %></p>

<h3 class="center-align header"><%= @course.code %>: <%= @course.name %> </h3>


<p class="text-muted">
  <%= @course.description %>
</p>

<p class="text-muted">
  <strong>Start date:</strong>
  <%= @course.start_date.to_date.to_formatted_s(:long) %><br>
  <strong>End date:</strong>
  <%= @course.end_date.to_date.to_formatted_s(:long) %>
</p>

<div class="center-align">
  <a class="waves-effect waves-light btn-large"><i class="material-icons left">fingerprint  </i>Enroll Now</a>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Tech University</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    
  </head>

  <body>
    <%= render 'shared/header' %>

    <main>
      <div class="container">
        <%= yield %>
      </div>
    </main>
    
    <%= render 'shared/footer' %> 
  </body>
</html>

app/views/pages/about.html.erb
<h1>Pages#about</h1>
<p>Find me in app/views/pages/about.html.erb</p>

app/views/pages/contact.html.erb
<h1>Pages#contact</h1>
<p>Find me in app/views/pages/contact.html.erb</p>

app/views/pages/home.html.erb
<h1>Pages#home</h1>
<p>Find me in app/views/pages/home.html.erb</p>

app/views/shared/_footer.html.erb
<footer class="page-footer">
  <div class="container">
    <div class="row">
      <div class="col l6 s12">
        <h5 class="white-text">Tech University</h5>
        <p class="grey-text text-lighten-4">The future of development training</p>
      </div>
      <div class="col l4 offset-l2 s12">
        <h5 class="white-text">Information</h5>
        <ul>
          <li><a class="grey-text text-lighten-3" href="#!">Help</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">About</a></li>
          <li><a class="grey-text text-lighten-3" href="#!">Contact us</a></li>
        </ul>
      </div>
    </div>
  </div>
  <div class="footer-copyright">
    <div class="container">
    © 2014 Tech University
    <a class="grey-text text-lighten-4 right" href="#!"></a>
    </div>
  </div>
</footer>

app/views/shared/_header.html.erb
<header>
  <ul id="dropdown1" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <ul id="dropdown2" class="dropdown-content">
    <li><a href="#!">one</a></li>
    <li><a href="#!">two</a></li>
    <li class="divider"></li>
    <li><a href="#!">three</a></li>
  </ul>
  <nav>
    <div class="nav-wrapper">
      <div class="container">
        <a href="#" class="brand-logo" id="test">Tech University</a>
        <a href="#" data-target="mobile" class="sidenav-trigger"><i class="material-icons">menu</i></a>
        <ul id="nav-mobile" class="right hide-on-med-and-down">
          <li><%= link_to 'Courses', courses_path %></li>
          <li><a href="#">Enrollments</a></li>
          <li><a class="dropdown-trigger" href="#!" data-target="dropdown1">Account<i class="material-icons right">arrow_drop_down</i></a></li>
        </ul>
      </div>
    </div>
  </nav>
  <ul class="sidenav" id="mobile">
    <li><%= link_to 'Courses', courses_path %></li>
    <li><a href="#">Enrollments</a></li>
    <li><a class="dropdown-trigger" href="#!" data-target="dropdown2">Account<i class="material-icons right">arrow_drop_down</i></a></li>
  </ul>
</header>